EXCLUDE = {
 "info@goodcrypto.app":"Round-1 research placed GoodCrypto in Ukraine; US location ('NY') conflicting and repos stale.",
 "support@gocharting.com":"Location conflicting (Chicago vs India); GoCharting appears India-based.",
 "info@quantscience.io":"Same person as PyQuant News (co-founder Jason Strimpel); kept the stronger PyQuant News record.",
 "info@epicflow.io":"No US state/city verifiable (GitHub shows only 'United States').",
 "help@daytradeu.com":"No US state/city verifiable (GitHub shows only 'United States').",
 "support@traddoo.com":"Reported as British Virgin Islands-registered prop firm; US presence unverified.",
 "luc@ou.edu":"Student project with university email; not a professional prospect.",
 "lmagama@gsumail.gram.edu":"Student project with university email; not a professional prospect.",
 "saahas.pulivarthi@gmail.com":"Student; location inferred from school only.",
 "rehanmollick07@utexas.edu":"Student buildathon project with university email.",
 "danielsp.dev@gmail.com":"Student; city inferred from school only.",
 "sririthishpalani@gmail.com":"Job-seeking student; location inferred from school.",
 "agarwalaashrut@gmail.com":"Student research project; location inferred from school.",
 "nouri.darien@gmail.com":"Research-focused, job-seeking student; weak automation intent.",
 "itstaejun@gmail.com":"Prospect states the trading system is shut down.",
 "dalronj.robertson@gmail.com":"Trading is an older side project; current focus is biomedical research.",
 "contact@jumpcrypto.com":"Very large trading firm; outsourcing custom bot work is not plausible.",
 "support@uniswap.org":"Large DeFi protocol support inbox; not a trading-automation buyer.",
 "hello@polymarket.com":"Large prediction-market operator; generic inbox, not a plausible buyer.",
 "founders@kalshi.com":"Large regulated exchange; not a plausible buyer.",
 "admin@ninjatrader.com":"Platform owner; generic admin inbox, not a plausible buyer.",
 "support@tastytrade.com":"Large broker support inbox; not a plausible buyer.",
 "hi@messari.io":"Research/data firm; no automation requirement evident.",
 "team@0xproject.com":"DEX infrastructure company; not a trading-bot buyer.",
 "contact@dydx.exchange":"Large DeFi exchange; not a plausible buyer.",
 "omer@chaoslabs.xyz":"DeFi risk-management platform, not trading automation.",
 "tech@openfinance.io":"Digital securities platform; may be inactive.",
 "kwade@mchughson.com":"Energy trading risk-management consultancy; weak trading-automation fit.",
 "kevin@tradeduel.finance":"Simulated trading games; surname unknown; weak fit.",
 "developers@delv.tech":"DeFi fixed-rate protocol; weak trading-automation fit.",
 "sharden007@gmail.com":"Duplicate of Shawn R. Harden; kept the business-domain address contact@harden-ai.com.",
}
REVIEW = {
 "support@tastyware.dev":"Location conflicting (Idaho vs earlier source placing the developer in Ecuador).",
 "support@simplertrading.com":"Email seen only in a third-party GitHub dataset copying their FAQ; confirm on their site.",
 "team@optionalpha.com":"Email from a 2019 archived copy of their privacy policy; may be outdated.",
 "info@econoday.com":"Economic data vendor; partnership angle only.",
 "info@digitalassetresearch.com":"Established data vendor; partnership angle only.",
 "support@tradinghours.com":"Market-hours data vendor; partnership angle only.",
 "sales@ivolatility.com":"Options data vendor; partnership angle only.",
 "apihelp@cqg.com":"Large platform vendor (API help inbox); partnership angle only.",
 "learn@spiderrock.net":"Mid-size institutional vendor; partnership angle only.",
 "accounts@blockhouse.capital":"accounts@ inbox may route to finance/admin.",
 "walter@whsmacon.com":"Business nature of whsmacon.com not verified.",
 "info@fractova.com":"Newark, DE address appears to be a registered-agent address.",
 "info@quantumbots.co":"Mixed public reviews; verify before outreach.",
 "contact@antoniohickey.com":"City not published (GitHub says 'South Florida').",
 "hello@jedm.dev":"Location is a county (Summit County, CO), not a city; trading is a side project.",
 "hello@zommalabs.com":"Main business is AI back-office agents; trading link is one product.",
 "moshe@quentin.software":"Finance/trading libraries are tooling, not a trading business.",
 "info@qedtrading.io":"Cheyenne, WY may be a registered-agent address.",
 # large companies / partnership-only
 "info@talos.com":"Large institutional vendor; partnership angle only.",
 "info@alpaca.markets":"Large broker API; partnership/referral angle only.",
 "support@topstep.com":"Mid-size prop firm support inbox; partnership angle only.",
 "techsupport@tradier.com":"Tech-support inbox at broker API; partnership angle only.",
 "support@lime.co":"Broker support inbox; partnership angle only.",
 "technology@tradovate.com":"Platform vendor (same group as NinjaTrader); partnership angle only.",
 "support@massive.com":"Market-data vendor support inbox; partnership angle only.",
 "success@intrinio.com":"Market-data vendor; partnership angle only.",
 "support@databento.com":"Market-data vendor support inbox; partnership angle only.",
 "support@thetadata.net":"Market-data vendor support inbox; partnership angle only.",
 "support@finnhub.io":"Market-data vendor support inbox; partnership angle only.",
 "solutions@barchart.com":"Mid-to-large data/tools vendor; partnership angle only.",
 "opensource@bitnomial.com":"Exchange open-source inbox; partnership angle only.",
 "support@aries.com":"Conflicting HQ (San Francisco vs Detroit).",
 "accounting@aitrade.ai":"Only public inbox is accounting@; route to technical lead.",
 "support@tradingoose.ai":"Email spelling differs from website domain (TradingGoose.ai); confirm before sending.",
 "products@ussoftwarepro.com":"Email domain differs from company website.",
 "hello@opyn.co":"Company activity level unverified.",
 "hello@panoptic.xyz":"DeFi protocol; one listing shows BVI entity.",
 "info@sericatrading.com":"Company activity level unverified.",
 "info@commandiv.com":"Public activity last seen 2018.",
 "info@oqtradetech.com":"Public activity last seen 2021.",
 "alphahunter2019@gmail.com":"Gmail inbox from 2019; activity unverified.",
 "contact@blankly.finance":"Project activity level unverified; city conflicting (Ann Arbor vs Chicago).",
 # competitors
 "admin@abfs.tech":"Prospect is itself a trading-systems developer; subcontract/partner angle.",
 "services@4xpip.com":"Sells custom EA programming (competitor); Casper, WY may be registered-agent address.",
 "support@api2trade.com":"Developer-tooling vendor; Sheridan, WY may be registered-agent address.",
 "contact@hashcashconsultants.com":"Software vendor (possible competitor); subcontract angle.",
 "coding.sigma@gmail.com":"Developer/educator (possible competitor); state inferred from 'San Diego'.",
 "mayeski@gmail.com":"HFT developer (possible competitor); partnership angle.",
 # missing city
 "contact@harden-ai.com":"City not published (state only).",
 "nguemechieu@live.com":"City not published (state only); possibly early-stage developer.",
 "presspage.entertainment@gmail.com":"City not found; state from company filing referenced in own repo.",
 "keith@algorithmicquantitative.com":"City not published (state only); activity unverified.",
 "SFitz911@gmail.com":"City not published (state only).",
}
