EXCLUDE = {
 "brightflag":"Product description not verified from any fetched page; no email; low confidence.",
}
REVIEW = {
 'welcome@stb-schelly.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'kontakt@schuermanngmbh.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'kanzlei@sus-leipzig.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@concept-steuer.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@finqle.nl':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'contact@us.getyooz.com':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@sebona.ch':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@akga.nl':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@kantoorask.nl':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@primus-audit.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'kanzlei@hhsg.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'sales@debitan.com':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'admin@sdgaccountant.com':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'inro@pronexusllc.com':'Email copied as displayed but looks like a typo of info@; confirm before sending.',
 'dpo@':'Only a data-protection inbox was found; find a business contact.',
 'bluechip':'Source page of email unclear in search result.',
 'propertyme.com':'Email may come from an app-store/G2 listing rather than the company site.',
 'aide@tiime.fr':'Email may come from an app listing rather than the contact page.',
 'productive.io':'Source page of email unclear in search result.',
 'connected@silverfin.com':'Email from official marketplace listing, not company site.',
 'support@moneybird.com':'Email from official X account post, not company site.',
 'info@billomat.com':'Found address in Nürnberg (worklist said Siegen); source attributed to Facebook profile.',
 'hello@bookkeeperpro.ca':"Site brands itself 'Blue Keel' — may duplicate the Blue Keel entry; check.",
 'ambiance':'Email only from Facebook page / directory listing.',
 'satago.com':'Search summary did not tie email to an exact company page.',
 'hokodo':'Search summary did not tie email to an exact company page.',
 'earlypay':'Search summary did not tie email to an exact company page.',
 'twenty32':'Search summary did not tie email to an exact company page.',
 'vdgaccountancy':'Search summary did not tie email to an exact company page; alternate harm@ address seen.',
 'debtordaddy':'Brand now CreditorWatch Collect; confirm current contact.',

 'skyhigherp':'Relevance based on company name only (no description published).',
 'lynxerp':'Relevance based on company name only (no description published).',
 'rmi':'Email domain differs from website; city inferred from website domain.',
 'suitesqr':'Website taken from email domain (not listed on GitHub).',

 'dezerx@bauerkuke-edv.de':'Email on parent company domain (Bauer & Kuke EDV).',
 'info@q-invoice.com':'Email domain differs from website field (qnvc.net).',
 'contact@shop2bill.com':'Email domain differs from website field (beembill.com).',
 'erp4all':'Website taken from email domain (not listed on GitHub).',

 'paytriot':'Public reviews mention unpaid-balance complaints; check before outreach.',
 'invoiceryt':'Relevance based on company name only (no description published).',
 'rootsaccounting':'Relevance based on company name only (no description published).',
 'atxaccounting':'Relevance based on company name only (no description published).',
 'thriveerp':'Relevance based on company name only (no description published).',
 'dennis@proceipt.com':'Email domain differs from website domain (same brand per GitHub org).',
 'fedix':'Email domain differs from website domain.',
 'whizconsulting':'Email domain differs from website domain.',
 'flashpayments':'Email domain differs from website domain.',
 'mgabookkeeping':'Website taken from email domain (not listed on GitHub).',

 "invoiceninja":"HQ conflicting between sources (US vs Israel); confirm before sending.",
 "fixflo":"Product/billing details not verified from a fetched page (GitHub confirmed location/email only).",
 "contact@debitura.com":"Country taken from GitHub location (USA) only; confirm HQ before sending.",
 "apisupport@storecove.com":"Technical API support inbox; find a business contact.",
 "norfello":"Country from domain + company form only.",
 "bluestar":"Country from domain + company form only.",
 "mintsystem":"Country from domain + company form only.",
 "coalesco":"Country from domain + company form only.",
 "dev@theconcept-technologies.com":"Company is also an AI automation agency (possible competitor/partner); city not verified.",
 "365businessdevelopment":"Country inferred from GmbH legal form only (could be DE/AT/CH).",
 "christoph.krieg@":"Country inferred from GmbH legal form only (could be DE/AT/CH).",
}
