EXCLUDE = {
 "fh@flogersoft.de":"Email on an individual developer's domain (flogersoft.de); earlier research classed it as an individual.",
 'invoiceleaf':'Country not verified (guessed from integration).',
 'jasy':"Email on an individual developer's domain (flogersoft.de); earlier research classed it as an individual.",
 'parleygroup':'Website/email are South African (.co.za); GitHub location conflicting.',

 "brightflag":"Product description not verified from any fetched page; no email; low confidence.",
}
REVIEW = {
 'circuly':'GitHub org archived Oct 2025; may be inactive.',
 'rechnungslotse':'Product inferred from company name only.',
 'ktilaskutus':'Product inferred from company name only.',
 'primedbilling':'State inferred from city name only.',
 'nordinvoice':'Country inferred from .nl domain + KvK support.',
 'liberu':'Earlier research classed Liberu as an open-source project; confirm it is a company.',
 'onguard':'Visma-owned; partnership angle.',
 'octobat':'Possibly acquired; confirm status.',
 'faktur':"Earlier research classed a 'Faktur' org as a hobby project; confirm.",
 'errasit':'Country inferred from legal form/domain.',
 'ihd':'Country inferred from legal form/domain.',
 'bosveldincasso':'Country inferred from domain/language.',
 'info@inkasso24.de':'Email domain differs from website (inkasso-24.de).',

 'info@hunki-enterprises.com':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'kontakt@itis.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@bnberatung.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'bruehl@gtkp.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@datag-nuernberg.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'collections@hiltonbaird.co.uk':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'ira@bulletprooftax.com':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'josh@feuerhelmlanger.com':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'assemblypayments':'Email from a staging copy of their API docs.',
 'hello@two.inc':'Source page of email unclear.',
 'info@fundthrough.com':'Source page of email unclear.',
 'ambition@maxa.ai':'Email from Facebook page only.',
 'enquiries@kreston':'Email from Kreston network member profile, not firm site.',
 'mailbox@swiftltd.ca':'Source page of email unclear.',
 'jmarker@nms-cpa.com':'Source page of email unclear.',
 'sales@clever-invoice.com':'Email from a directory page run by the operator.',
 'billy@billy.dk':'Source page of email unclear.',
 'info@kivra.com':'Source page of email unclear.',
 'johannes@monetax.se':'Source page of email unclear.',
 'info@unifiedpost.com':'Source page of email unclear.',
 'acysos':'Source page of email unclear.',
 'opennet':'Source page of email unclear.',
 'ufficio@mkt.it':'Source page of email unclear.',
 'keyadmin':'Source page of email unclear.',
 'byogroup':'Source page of email unclear.',
 'empirebookkeeping':'Email from contact page or Yellow Pages (unclear).',

 'welcome@stb-schelly.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'kontakt@schuermanngmbh.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'kanzlei@sus-leipzig.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@concept-steuer.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@finqle.nl':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'contact@us.getyooz.com':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@sebona.ch':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@akga.nl':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@kantoorask.nl':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'info@primus-audit.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'kanzlei@hhsg.de':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'sales@debitan.com':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'admin@sdgaccountant.com':"Email domain differs from listed website (shown on the company's own page); confirm.",
 'inro@pronexusllc.com':'Email copied as displayed but looks like a typo of info@; confirm before sending.',
 'dpo@':'Only a data-protection inbox was found; find a business contact.',
 'bluechip':'Source page of email unclear in search result.',
 'propertyme.com':'Email may come from an app-store/G2 listing rather than the company site.',
 'aide@tiime.fr':'Email may come from an app listing rather than the contact page.',
 'productive.io':'Source page of email unclear in search result.',
 'connected@silverfin.com':'Email from official marketplace listing, not company site.',
 'support@moneybird.com':'Email from official X account post, not company site.',
 'info@billomat.com':'Found address in Nürnberg (worklist said Siegen); source attributed to Facebook profile.',
 'hello@bookkeeperpro.ca':"Site brands itself 'Blue Keel' — may duplicate the Blue Keel entry; check.",
 'ambiance':'Email only from Facebook page / directory listing.',
 'satago.com':'Search summary did not tie email to an exact company page.',
 'hokodo':'Search summary did not tie email to an exact company page.',
 'earlypay':'Search summary did not tie email to an exact company page.',
 'twenty32':'Search summary did not tie email to an exact company page.',
 'vdgaccountancy':'Search summary did not tie email to an exact company page; alternate harm@ address seen.',
 'debtordaddy':'Brand now CreditorWatch Collect; confirm current contact.',

 'skyhigherp':'Relevance based on company name only (no description published).',
 'lynxerp':'Relevance based on company name only (no description published).',
 'rmi':'Email domain differs from website; city inferred from website domain.',
 'suitesqr':'Website taken from email domain (not listed on GitHub).',

 'dezerx@bauerkuke-edv.de':'Email on parent company domain (Bauer & Kuke EDV).',
 'info@q-invoice.com':'Email domain differs from website field (qnvc.net).',
 'contact@shop2bill.com':'Email domain differs from website field (beembill.com).',
 'erp4all':'Website taken from email domain (not listed on GitHub).',

 'paytriot':'Public reviews mention unpaid-balance complaints; check before outreach.',
 'invoiceryt':'Relevance based on company name only (no description published).',
 'rootsaccounting':'Relevance based on company name only (no description published).',
 'atxaccounting':'Relevance based on company name only (no description published).',
 'thriveerp':'Relevance based on company name only (no description published).',
 'dennis@proceipt.com':'Email domain differs from website domain (same brand per GitHub org).',
 'fedix':'Email domain differs from website domain.',
 'whizconsulting':'Email domain differs from website domain.',
 'flashpayments':'Email domain differs from website domain.',
 'mgabookkeeping':'Website taken from email domain (not listed on GitHub).',

 "invoiceninja":"HQ conflicting between sources (US vs Israel); confirm before sending.",
 "fixflo":"Product/billing details not verified from a fetched page (GitHub confirmed location/email only).",
 "contact@debitura.com":"Country taken from GitHub location (USA) only; confirm HQ before sending.",
 "apisupport@storecove.com":"Technical API support inbox; find a business contact.",
 "norfello":"Country from domain + company form only.",
 "bluestar":"Country from domain + company form only.",
 "mintsystem":"Country from domain + company form only.",
 "coalesco":"Country from domain + company form only.",
 "dev@theconcept-technologies.com":"Company is also an AI automation agency (possible competitor/partner); city not verified.",
 "365businessdevelopment":"Country inferred from GmbH legal form only (could be DE/AT/CH).",
 "christoph.krieg@":"Country inferred from GmbH legal form only (could be DE/AT/CH).",
}
